---
- hosts: "{{ host }}"
  remote_user: root

  tasks:

  - name: Install pip
    ansible.builtin.apt:
      name: python3-pip
      state: present
      update_cache: yes

  - name: Install honeyservice package
    ansible.builtin.pip:
      name: git+https://github.com/DeceptionProjects/FakeNetworkServices.git

  - name: Run honey ssh server
    command: python3 -m fake_network_services.FakeNetworkService -p 8000 -s ssh -l {{ elasticsearch_server }} --api-key="{{ elasticsearch_api_key }}"
    async: 1000
    poll: 0