---
- hosts: "{{ host }}"
  remote_user: root

  tasks:
    - name: Remove automatic updates
      apt:
        name: unattended-upgrades
        state: absent

    - name: Base dependencies
      apt:
        pkg:
          - nmap
          - ncat
          - python3
          - python3-pip
          - net-tools
          - unzip
        state: present
        update_cache: yes
