services:
  attacker:
    build:
      context: .
      dockerfile: attacker/incalmo.Dockerfile
    volumes:
      - ./attacker:/attacker
    # environment:
    #   - SERVER_IP=localhost:8888
    #   - PYTHONUNBUFFERED=1
    # command: /bin/bash -c "while true; do sleep 1; done" # Keep container running for development

networks:
  dev_network:
    driver: bridge
