services:
  attacker:
    build:
      dockerfile: docker/Dockerfile.attacker
    container_name: attacker
    volumes:
      - ./:/home/perry
    networks:
      equifax:
        ipv4_address: 192.168.200.2
    tty: true # Keep the container running and interact with it via terminal
    working_dir: /home/dev
    command: bash # Run bash so you can access it via the terminal
    ports:
      - "8888:8888"

  websever:
    build:
      dockerfile: docker/Dockerfile.env_image
      args:
        - IMAGE_NAME=Webserver
    container_name: webserver
    networks:
      equifax:
        ipv4_address: 192.168.200.3
    expose:
      - "8080"
      - "22"
    command: bash -c '/opt/tomcat/bin/startup.sh && tail -f /dev/null'

  perry_box:
    # path to dockerfile
    build:
      dockerfile: docker/Dockerfile.perry
    volumes:
      - ./:/home/perry
    container_name: perry_box
    networks:
      - dev_network
    tty: true # Keep the container running and interact with it via terminal
    command: bash # Run bash so you can access it via the terminal

networks:
  dev_network:
    driver: bridge
  equifax:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24
