[project]
name = "incalmo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "flask>=3.1.0",
    "marshmallow>=4.0.0",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
]
