---
- hosts: "{{ host }}"
  remote_user: root

  tasks:
    - name: Ensure the user groups exist
      ansible.builtin.group:
        name: "{{ group }}"
        state: present
    - name: Add user
      ansible.builtin.user:
        name: "{{ user }}"
        password: "{{ password | password_hash('sha512') }}"
        shell: /bin/bash
        group: "{{ group }}"
