---
- hosts: "{{ host }}"
  remote_user: root

  tasks:
    - name: Ensure sudo lecture is disabled
      lineinfile:
        path: /etc/sudoers.d/disable_lecture
        state: present
        line: 'Defaults lecture=never'
        create: yes
        owner: root
        group: root
        mode: '0440'

    - name: Change permissions of /etc/sudoers to be writable by all users
      file:
        path: /etc/sudoers
        mode: '0755'
        owner: root
        group: root