---
- hosts: "{{ host }}"
  remote_user: root

  tasks:
  - name: Enable sshd password login
    become: true
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regex: "^(#)?{{item.key}}"
      line: "{{item.key}} {{item.value}}"
      state: present
    loop:
      - { key: "PasswordAuthentication", value: "yes" }
    notify:
      - restart sshd

  handlers:
    - name: restart sshd
      command: service sshd restart
      become: true