---
- hosts: "{{ host }}"
  remote_user: root

  vars:
    weak_passwords: "{{ lookup('file', '10k-most-common.txt') }}"

  tasks:
  - name: Set weak password for user
    ansible.builtin.user:
      name: "{{ user }}"
      password: "{{ item | password_hash('sha512') }}"
    with_random_choice: "{{ weak_passwords.split('\n') }}"
    become: true