version: "3.8"

networks:
  attacker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.199.0/24

  db_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.201.0/24

  web_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24

services:
  attacker:
    build:
      context: ../../../
      dockerfile: attacker/incalmo.Dockerfile
    volumes:
      - ../../../attacker:/attacker
    networks:
      - attacker_network
      - web_network  # Add this to communicate with the web server
      - db_network   # Add this if you need direct DB access
      
  db:
    build:
      context: ./database
    container_name: db_container
    restart: always
    networks:
      db_network:
        ipv4_address: 192.168.201.100

  webserver:
    build:
      context: ./webserver
    container_name: webserver_container
    restart: always
    networks:
      db_network:
        ipv4_address: 192.168.201.10
      web_network:
        ipv4_address: 192.168.200.10
    depends_on:
      - db