networks:
  attacker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.199.0/24

  web_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24

  db_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.201.0/24

services:
  attacker:
    build:
      context: ../
      dockerfile: docker/attacker/incalmo.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../incalmo/api:/incalmo/incalmo/api
      - ../incalmo/c2server:/incalmo/incalmo/c2server
      - ../incalmo/core:/incalmo/incalmo/core
      - ../incalmo/models:/incalmo/incalmo/models
      - ../incalmo/__init__.py:/incalmo/incalmo/__init__.py
      - ../incalmo/exceptions.py:/incalmo/incalmo/exceptions.py
      - ../incalmo/incalmo_runner.py:/incalmo/incalmo/incalmo_runner.py
      - ../incalmo/server.py:/incalmo/incalmo/server.py
      - ../config/:/incalmo/config
      - ../output/:/incalmo/output
      - venv-volume:/incalmo/.venv
    networks:
      attacker_network:
        ipv4_address: 192.168.199.10
      web_network:    
        ipv4_address: 192.168.200.10 
    ports:
      - 8888:8888
      - 5678:5678

  webserver:
    build:
      context: ./equifax/webserver
    container_name: webserver_container
    restart: always
    networks:
      db_network:
        ipv4_address: 192.168.201.20
      web_network:
        ipv4_address: 192.168.200.20
    ports:
      - 8080:8080

  db:
    build:
      context: ./equifax/database
    container_name: db_container
    restart: always
    networks:
      db_network:
        ipv4_address: 192.168.201.100

volumes:
  venv-volume: