networks:
  attacker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.199.0/24

  web_1_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24
  
  web_2_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.201.0/24

services:
  attacker:
    build:
      context: ../
      dockerfile: docker/attacker/incalmo.Dockerfile
    env_file:
      - ../.env
    environment:
      - SERVER_IP=localhost
      - MODE=docker
      - DEBUG=true
    volumes:
      - ../:/incalmo
      - frontend-ignore:/incalmo/incalmo/frontend
      - venv-volume:/incalmo/.venv
    networks:
      attacker_network:
        ipv4_address: 192.168.199.10
      web_1_network:    
        ipv4_address: 192.168.200.10 
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:6379:6379"
      - "127.0.0.1:5678:5678"

  webserver_1:
    build:
      context: ./equifax/webserver
    container_name: webserver_1_container
    restart: always
    networks:
      attacker_network:
        ipv4_address: 192.168.199.20
      web_1_network:
        ipv4_address: 192.168.200.20

  webserver_2:
    build:
      context: ./equifax/webserver
    container_name: webserver_2_container
    restart: always
    networks:
      web_1_network:
        ipv4_address: 192.168.200.30
      web_2_network:
        ipv4_address: 192.168.201.30

volumes:
  venv-volume:
  frontend-ignore:
