---
- hosts: "{{ host }}"
  remote_user: root

  tasks:
  - name: Change password
    ansible.builtin.user:
      name: "{{ user }}"
      password: "{{ password | password_hash('sha512') }}"
    become: true