---
- hosts: "{{ host }}"
  remote_user: root

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ cpath }}"
        state: directory
        mode: "{{ dmode }}"
