---
- hosts: "{{ host }}"
  tasks:
    - name: create .ssh directory
      become: true
      become_user: "{{ host_user }}"
      file:
        path: "~/.ssh"
        state: directory
        mode: "0700"

    - name: add to ssh config
      become: true
      become_user: "{{ host_user }}"
      blockinfile:
        state: present
        insertafter: EOF
        dest: "~/.ssh/config"
        content: |
          Host {{ follower_user }}
            HostName {{ follower }}
            User {{ follower_user }}
            IdentityFile ~/.ssh/id_rsa
        create: true
        mode: "0600"
        marker: ""
