- name: Join Ubuntu machines to the domain and set DNS server
  hosts: "{{ host }}"
  remote_user: root
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Update DNS nameserver in resolved.conf
      become: true
      lineinfile:
        path: /etc/systemd/resolved.conf
        line: "DNS=192.168.200.3 8.8.8.8"
        regexp: '^(#)?(DNS=).*'

    - name: Restart systemd-resolved service
      service:
        name: systemd-resolved
        state: restarted

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - realmd
        - oddjob
        - oddjob-mkhomedir
        - sssd
        - samba-common-bin
        - adcli
        - sssd-tools
        - krb5-user
    
    - name: Copy krb5.conf to remote machine
      template:
        src: krb5.conf.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy sssd.conf to remote machine
      template:
        src: sssd.conf.j2
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: '0600'
