---
- hosts: "{{ host }}"
  remote_user: root

  tasks:
  - name: Copy sudo.deb
    copy:
      src: sudo_1.8.19p1-2.1_amd64.deb
      dest: /tmp/sudo_1.8.19p1-2.1_amd64.deb

  - name: Install sudo
    apt:
      deb: /tmp/sudo_1.8.19p1-2.1_amd64.deb
      state: present
      force: yes
